/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uas;

import java.io.IOException;
import javax.swing.JScrollPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alwan
 * Class ini adalah kelas untuk registrasi akun
 * Class ini menerapkan design pattern template pada method clearForm(),check(), dan keHome();
 */
public class RegisterForm extends javax.swing.JPanel implements data {

    
    public final JScrollPane contentScrollPane;
    public RegisterForm(JScrollPane contentScrollPane) {
        initComponents();
        this.contentScrollPane = contentScrollPane;
        regRegister1.setEnabled(false);
        check();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pwdRegister = new javax.swing.JPasswordField();
        konPwdRegister = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logRegister = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        regRegister1 = new javax.swing.JButton();
        nimRegister = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kelasRegist = new javax.swing.JTextField();
        namaRegist = new javax.swing.JTextField();
        errorNama = new javax.swing.JLabel();
        errorKelas = new javax.swing.JLabel();
        errorNim = new javax.swing.JLabel();
        errorPassword = new javax.swing.JLabel();
        errorKonPassword = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(30, 29, 29));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        pwdRegister.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        pwdRegister.setPreferredSize(new java.awt.Dimension(800, 1000));
        pwdRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdRegisterActionPerformed(evt);
            }
        });
        pwdRegister.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwdRegisterKeyReleased(evt);
            }
        });
        add(pwdRegister);
        pwdRegister.setBounds(327, 214, 170, 23);

        konPwdRegister.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        konPwdRegister.setPreferredSize(new java.awt.Dimension(800, 1000));
        konPwdRegister.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                konPwdRegisterKeyReleased(evt);
            }
        });
        add(konPwdRegister);
        konPwdRegister.setBounds(327, 244, 170, 23);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM REGISTRASI");
        add(jLabel1);
        jLabel1.setBounds(190, 30, 300, 80);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIM");
        jLabel2.setPreferredSize(new java.awt.Dimension(800, 1000));
        add(jLabel2);
        jLabel2.setBounds(194, 184, 21, 16);

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jLabel3.setPreferredSize(new java.awt.Dimension(800, 1000));
        add(jLabel3);
        jLabel3.setBounds(194, 214, 56, 16);

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Konfirmasi Password");
        jLabel4.setPreferredSize(new java.awt.Dimension(800, 1000));
        add(jLabel4);
        jLabel4.setBounds(194, 244, 119, 16);

        logRegister.setBackground(new java.awt.Color(24, 118, 211));
        logRegister.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        logRegister.setForeground(new java.awt.Color(255, 255, 255));
        logRegister.setText("Masuk");
        logRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logRegisterActionPerformed(evt);
            }
        });
        add(logRegister);
        logRegister.setBounds(330, 350, 170, 26);

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sudah memiliki akun?");
        add(jLabel5);
        jLabel5.setBounds(350, 330, 150, 14);

        regRegister1.setBackground(new java.awt.Color(24, 118, 211));
        regRegister1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        regRegister1.setForeground(new java.awt.Color(255, 255, 255));
        regRegister1.setText("Registrasi");
        regRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regRegister1ActionPerformed(evt);
            }
        });
        add(regRegister1);
        regRegister1.setBounds(330, 290, 170, 26);

        nimRegister.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        nimRegister.setPreferredSize(new java.awt.Dimension(800, 1000));
        nimRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimRegisterActionPerformed(evt);
            }
        });
        nimRegister.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nimRegisterKeyReleased(evt);
            }
        });
        add(nimRegister);
        nimRegister.setBounds(327, 184, 170, 23);

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama");
        jLabel6.setPreferredSize(new java.awt.Dimension(800, 1000));
        add(jLabel6);
        jLabel6.setBounds(194, 126, 34, 16);

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kelas");
        jLabel7.setPreferredSize(new java.awt.Dimension(800, 1000));
        add(jLabel7);
        jLabel7.setBounds(194, 156, 32, 16);

        kelasRegist.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        kelasRegist.setPreferredSize(new java.awt.Dimension(800, 1000));
        kelasRegist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasRegistActionPerformed(evt);
            }
        });
        kelasRegist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kelasRegistKeyReleased(evt);
            }
        });
        add(kelasRegist);
        kelasRegist.setBounds(327, 155, 170, 23);

        namaRegist.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        namaRegist.setPreferredSize(new java.awt.Dimension(800, 1000));
        namaRegist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                namaRegistKeyReleased(evt);
            }
        });
        add(namaRegist);
        namaRegist.setBounds(327, 126, 170, 23);

        errorNama.setBackground(new java.awt.Color(255, 0, 0));
        errorNama.setForeground(new java.awt.Color(255, 255, 255));
        errorNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                errorNamaKeyReleased(evt);
            }
        });
        add(errorNama);
        errorNama.setBounds(520, 130, 200, 20);

        errorKelas.setBackground(new java.awt.Color(255, 0, 51));
        errorKelas.setForeground(new java.awt.Color(255, 255, 255));
        add(errorKelas);
        errorKelas.setBounds(520, 160, 200, 20);

        errorNim.setBackground(new java.awt.Color(255, 0, 51));
        errorNim.setForeground(new java.awt.Color(255, 255, 255));
        errorNim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                errorNimKeyReleased(evt);
            }
        });
        add(errorNim);
        errorNim.setBounds(520, 190, 200, 20);

        errorPassword.setBackground(new java.awt.Color(255, 0, 51));
        errorPassword.setForeground(new java.awt.Color(255, 255, 255));
        errorPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                errorPasswordKeyReleased(evt);
            }
        });
        add(errorPassword);
        errorPassword.setBounds(520, 220, 200, 20);

        errorKonPassword.setBackground(new java.awt.Color(255, 0, 51));
        errorKonPassword.setForeground(new java.awt.Color(255, 255, 255));
        add(errorKonPassword);
        errorKonPassword.setBounds(520, 250, 230, 20);

        jPanel1.setBackground(new java.awt.Color(206, 208, 210));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sipadu.png"))); // NOI18N
        jLabel8.setText("SIPADU");
        jPanel1.add(jLabel8);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 160, 1500);
    }// </editor-fold>//GEN-END:initComponents

    private void pwdRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdRegisterActionPerformed
  
    private void logRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logRegisterActionPerformed
        // TODO add your handling code here:
        keHome();
        
    }//GEN-LAST:event_logRegisterActionPerformed
    //method ini untuk meregister new value ke database
    private void regRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regRegister1ActionPerformed
        // TODO add your handling code here:
        Mahasiswa mhs = new Mahasiswa();
       
        
        String nama= namaRegist.getText();
        String kelas = kelasRegist.getText();
        String nim = nimRegister.getText();
        String pwd = pwdRegister.getText();
        String kon = konPwdRegister.getText();
        mhs.setNim(nim);
        mhs.setPassword(pwd);
        mhs.setNama(nama);
        mhs.setKelas(kelas);
        if(nama!=""||kelas!=""||nim!=""||pwd!=""){
        if(kon == null ? pwd == null : kon.equals(pwd)){
            
            try {
                Database.getInstance().registMahasiswa(mhs);
                JOptionPane.showMessageDialog(this, "Sukses Tersimpan");
                clearForm();
                regRegister1.setEnabled(false);
            } catch (SQLException | IOException ex) {
                Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Gagal Menyimpan Data");
            }
                
        } else{
            JOptionPane.showMessageDialog(this, "Gagal Menyimpan Data");
        }
      }check();
      
      
    }//GEN-LAST:event_regRegister1ActionPerformed

    private void nimRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimRegisterActionPerformed

    private void kelasRegistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasRegistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasRegistActionPerformed

    private void errorNimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_errorNimKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_errorNimKeyReleased

    private void errorPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_errorPasswordKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_errorPasswordKeyReleased
    //method ini untuk cek validasi sesuai kolom yang dimaksud
    private void pwdRegisterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdRegisterKeyReleased
        // TODO add your handling code here:
        String pwd = pwdRegister.getText();
        if(pwd==""){
            regRegister1.setEnabled(false);
        }
        if(pwd.length()<8){
            errorPassword.setText("Password harus > 8 karakter!");
            regRegister1.setEnabled(false);
        }else{
            errorPassword.setText("");
        }check();
    }//GEN-LAST:event_pwdRegisterKeyReleased
    //method ini untuk cek validasi sesuai kolom yang dimaksud
    private void nimRegisterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nimRegisterKeyReleased
        // TODO add your handling code here:
        String input = nimRegister.getText();
        if(input==""){
            regRegister1.setEnabled(false);
        }
        if (input.matches("[0-9]*")) {
            errorNim.setText("");
            
        } else {
            errorNim.setText("Inputan harus angka");
            regRegister1.setEnabled(false);
        }check();
    }//GEN-LAST:event_nimRegisterKeyReleased

    private void errorNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_errorNamaKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_errorNamaKeyReleased
//method ini untuk cek validasi sesuai kolom yang dimaksud
    private void namaRegistKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaRegistKeyReleased
        // TODO add your handling code here:
        String REGEX = ".*[&%$#@!~]+.*";
        String nama = namaRegist.getText();
        
        if(nama==""){
            regRegister1.setEnabled(false);
        }
        if (!nama.matches(REGEX)) {
            errorNama.setText("");
            
        } else {
            errorNama.setText("Tidak boleh ada karakter spesial");
            regRegister1.setEnabled(false);
        }
        
        check();
    }//GEN-LAST:event_namaRegistKeyReleased
//method ini untuk cek validasi sesuai kolom yang dimaksud
    private void kelasRegistKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kelasRegistKeyReleased
        // TODO add your handling code here:
        String REGEX = ".*[&%$#@!~]+.*";
        String nama = kelasRegist.getText();
        if(nama==""){
            regRegister1.setEnabled(false);
        }
        
        if (!nama.matches(REGEX)) {
            errorKelas.setText("");
            
        } else {
            errorKelas.setText("Tidak boleh ada karakter spesial");
            regRegister1.setEnabled(false);
        }check();
    }//GEN-LAST:event_kelasRegistKeyReleased
//method ini untuk cek validasi sesuai kolom yang dimaksud
    private void konPwdRegisterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_konPwdRegisterKeyReleased
        // TODO add your handling code here:
        String pwd = pwdRegister.getText();
        String kon = konPwdRegister.getText();
        if(kon==""){
            regRegister1.setEnabled(false);
        }
        
        if (kon.matches(pwd)) {
            errorKonPassword.setText("");
            regRegister1.setEnabled(true);
            
        } else {
            errorKonPassword.setText("Input berbeda dengan password");
            regRegister1.setEnabled(false);
        }check();
        
    }//GEN-LAST:event_konPwdRegisterKeyReleased
//method ini untuk cek validasi sesuai value yang termaksud
    @Override
    public void check(){
        String nama= namaRegist.getText().toString();
        String kelas = kelasRegist.getText().toString();
        String nim = nimRegister.getText().toString();
        String pwd = pwdRegister.getText().toString();
        String kon = konPwdRegister.getText().toString();
        if((nama==""||kelas==""||nim==""||pwd== ""||kon=="")){
            regRegister1.setEnabled(false);
        }
    }
    //method ini untuk membersihkan textfield
    @Override
    public void clearForm(){
         namaRegist.setText("");
        kelasRegist.setText("");
        nimRegister.setText("");
        pwdRegister.setText("");
        konPwdRegister.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorKelas;
    private javax.swing.JLabel errorKonPassword;
    private javax.swing.JLabel errorNama;
    private javax.swing.JLabel errorNim;
    private javax.swing.JLabel errorPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kelasRegist;
    private javax.swing.JPasswordField konPwdRegister;
    private javax.swing.JButton logRegister;
    private javax.swing.JTextField namaRegist;
    private javax.swing.JTextField nimRegister;
    private javax.swing.JPasswordField pwdRegister;
    private javax.swing.JButton regRegister1;
    // End of variables declaration//GEN-END:variables

    //method ini untuk kembali ke halaman utama
    @Override
    public void keHome() {
        contentScrollPane.setViewportView(new LoginPanel(contentScrollPane));
        }
}
